export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const ADD_TODO_LIST = 'ADD_TODO_LIST';
export const DELETE_TODO_LIST = 'DELETE_TODO_LIST';
export const CHANGE_LIST_ITEM_TITLE_VALUE = 'CHANGE_LIST_ITEM_TITLE_VALUE';
export const CHANGE_PROCESS_STATUS = 'CHANGE_PROCESS_STATUS';
export const CHANGE_TAB_STATUS = 'CHANGE_TAB_STATUS';
